### ISSUE TITLE
Unused `Input` React Component

### ISSUE THREAD

**Issue by honmanyau** [RandellDawson/pr-relations#4]
The `Input` React component is currently unused because of an earlier issues with using refs for handling focus. According to the [documentation](https://reactjs.org/docs/refs-and-the-dom.html), it appears that part of the issue that what was attempted was not working is because `Input` is a function component.

[`ref` forwarding](https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-to-dom-components), which is available with React 16.3 or later, is recommended for this type of situation. Given what was discussed regarding the use of `refs`, the following sentence found in the documentation for `ref` forwading may be of interest:

> These components tend to be used throughout the application in a similar manner as a regular DOM button and input, and accessing their DOM nodes may be unavoidable for managing focus, selection, or animations.

In any case, the code can be tidied up by using `React.forwardRef()`!

**Comment by RandellDawson** [comment]
Closed due to PR #5
